# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MyQLcqodZIbWhR0sYkU3mfromHwY5t4
"""

import streamlit as st
import pandas as pd
import pickle
import gzip

st.set_page_config(
    page_title="Sistema Preditivo de Obesidade",
    page_icon="🏥",
    layout="centered"
)

st.title("🏥 Sistema Preditivo de Obesidade")
st.markdown("Predição baseada em idade, altura e peso.")

@st.cache_resource
def carregar_modelo():
    with gzip.open("modelo.pkl.gz", "rb") as f:
        model = pickle.load(f)
    colunas = pickle.load(open("colunas.pkl", "rb"))
    return model, colunas

model, colunas = carregar_modelo()

st.subheader("📋 Dados do Paciente")

age = st.number_input("Idade", 14, 70)
height = st.number_input("Altura (m)", 1.40, 2.10)
weight = st.number_input("Peso (kg)", 40, 250)

if st.button("🔍 Realizar Predição"):

    input_df = pd.DataFrame([[age, height, weight]], columns=colunas)

    prediction = model.predict(input_df)[0]
    proba = model.predict_proba(input_df)

    st.success(f"📊 Nível previsto: **{prediction}**")

    prob_df = pd.DataFrame({
        "Classe": model.classes_,
        "Probabilidade": proba[0]
    }).sort_values(by="Probabilidade", ascending=False)

    st.dataframe(prob_df, use_container_width=True)