# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MyQLcqodZIbWhR0sYkU3mfromHwY5t4
"""

import streamlit as st
import pandas as pd
import pickle
import gzip

# ----------------------------
# CONFIGURAÇÃO DA PÁGINA
# ----------------------------
st.set_page_config(
    page_title="Sistema Preditivo de Obesidade",
    page_icon="🏥",
    layout="centered"
)

st.title("🏥 Sistema Preditivo de Obesidade")
st.markdown("Predição baseada em idade, altura e peso.")

# ----------------------------
# CARREGAR MODELO
# ----------------------------
@st.cache_resource
def carregar_modelo():
    with gzip.open("modelo.pkl.gz", "rb") as f:
        model = pickle.load(f)
    return model

model = carregar_modelo()

# ----------------------------
# INPUTS
# ----------------------------
st.subheader("📋 Dados do Paciente")

age = st.number_input("Idade", min_value=14, max_value=80, value=25)
height = st.number_input("Altura (m)", min_value=1.40, max_value=2.20, value=1.70)
weight = st.number_input("Peso (kg)", min_value=40, max_value=250, value=70)

# ----------------------------
# PREDIÇÃO
# ----------------------------
if st.button("🔍 Realizar Predição"):

    # Criar DataFrame exatamente como foi treinado
    input_df = pd.DataFrame({
        "Age": [age],
        "Height": [height],
        "Weight": [weight]
    })

    prediction = model.predict(input_df)[0]
    proba = model.predict_proba(input_df)

    st.success(f"📊 Nível previsto: **{prediction}**")

    st.subheader("Probabilidade por Classe")

    prob_df = pd.DataFrame({
        "Classe": model.classes_,
        "Probabilidade": proba[0]
    }).sort_values(by="Probabilidade", ascending=False)

    st.dataframe(prob_df, use_container_width=True)